"""
Trading Service Metrics
Prometheus metrics for the trading service
"""

from prometheus_client import Counter, Gauge, Histogram, Summary
from typing import Dict, Any

class TradingMetrics:
    """Metrics collection for trading service"""
    
    def __init__(self):
        # Trading metrics
        self.orders_total = Counter(
            'trading_orders_total', 
            'Total orders processed', 
            ['status', 'symbol', 'action']
        )
        
        self.order_latency_seconds = Histogram(
            'trading_order_latency_seconds',
            'Order processing latency in seconds',
            ['symbol', 'action']
        )
        
        self.pnl_total = Gauge(
            'trading_pnl_total',
            'Total P&L across all positions'
        )
        
        self.positions_active = Gauge(
            'trading_positions_active',
            'Number of active positions'
        )
        
        self.portfolio_value = Gauge(
            'trading_portfolio_value',
            'Total portfolio value'
        )
        
        # Strategy metrics
        self.strategy_signals_generated = Counter(
            'trading_strategy_signals_generated',
            'Signals generated by strategy',
            ['strategy', 'signal_type']
        )
        
        self.strategy_signals_executed = Counter(
            'trading_strategy_signals_executed',
            'Signals that resulted in trades',
            ['strategy', 'signal_type']
        )
        
        # Risk metrics
        self.risk_exposure_total = Gauge(
            'trading_risk_exposure_total',
            'Total risk exposure'
        )
        
        self.risk_position_size_limit = Gauge(
            'trading_risk_position_size_limit',
            'Position size limit'
        )
        
        # Service metrics
        self.requests_total = Counter(
            'trading_requests_total',
            'Total HTTP requests',
            ['method', 'endpoint', 'status']
        )
        
        self.request_duration_seconds = Histogram(
            'trading_request_duration_seconds',
            'HTTP request duration in seconds',
            ['method', 'endpoint']
        )
        
        # Error metrics
        self.errors_total = Counter(
            'trading_errors_total',
            'Total errors',
            ['error_type', 'service']
        )

# Global metrics instance
trading_metrics = TradingMetrics()

def record_trade_execution(symbol: str, action: str, status: str, duration: float):
    """Record trade execution metrics"""
    trading_metrics.orders_total.labels(
        status=status, 
        symbol=symbol, 
        action=action
    ).inc()
    
    trading_metrics.order_latency_seconds.labels(
        symbol=symbol, 
        action=action
    ).observe(duration)

def record_strategy_signal(strategy: str, signal_type: str, executed: bool = False):
    """Record strategy signal metrics"""
    trading_metrics.strategy_signals_generated.labels(
        strategy=strategy, 
        signal_type=signal_type
    ).inc()
    
    if executed:
        trading_metrics.strategy_signals_executed.labels(
            strategy=strategy, 
            signal_type=signal_type
        ).inc()

def update_portfolio_metrics(portfolio_value: float, positions_count: int, pnl: float):
    """Update portfolio metrics"""
    trading_metrics.portfolio_value.set(portfolio_value)
    trading_metrics.positions_active.set(positions_count)
    trading_metrics.pnl_total.set(pnl)

def update_risk_metrics(exposure: float, position_limit: float):
    """Update risk metrics"""
    trading_metrics.risk_exposure_total.set(exposure)
    trading_metrics.risk_position_size_limit.set(position_limit)

def record_request(method: str, endpoint: str, status: int, duration: float):
    """Record HTTP request metrics"""
    trading_metrics.requests_total.labels(
        method=method, 
        endpoint=endpoint, 
        status=str(status)
    ).inc()
    
    trading_metrics.request_duration_seconds.labels(
        method=method, 
        endpoint=endpoint
    ).observe(duration)

def record_error(error_type: str, service: str = "trading-service"):
    """Record error metrics"""
    trading_metrics.errors_total.labels(
        error_type=error_type, 
        service=service
    ).inc() 