#!/usr/bin/env python3
"""
SignalValidator service for Strategy Engine Testing Framework
Validates trading signals and their quality
"""

import asyncio
import pandas as pd
from typing import Dict, Any, List, Optional, Tuple
from datetime import datetime

from ..models import (
    SignalAction, ValidationStatus, SignalValidation, 
    StrategyTestResult, TestStatus, TestType
)


class SignalValidator:
    """
    Validates trading signals and their quality
    
    Tests signal generation, timing, consistency, and edge case handling
    """
    
    def __init__(self):
        """Initialize signal validator"""
        self.min_confidence_threshold = 0.5
        self.max_confidence_threshold = 1.0
        self.timing_tolerance_bars = 2
    
    async def validate_signals(self, strategy, mock_data: pd.DataFrame, 
                             symbol: str, config: Dict[str, Any]) -> List[SignalValidation]:
        """
        Validate signals generated by a strategy
        
        Args:
            strategy: Strategy instance to test
            mock_data: Mock market data for testing
            symbol: Trading symbol
            config: Test configuration
            
        Returns:
            List of SignalValidation results
        """
        signal_validations = []
        
        try:
            # Generate signals for the mock data
            signals = await self._generate_signals_for_data(strategy, mock_data, symbol, config)
            
            # Validate each signal
            for signal_data in signals:
                validation = await self._validate_single_signal(
                    signal_data, mock_data, symbol, config
                )
                signal_validations.append(validation)
            
        except Exception as e:
            # Create error validation
            error_validation = SignalValidation(
                strategy_name=strategy.name,
                symbol=symbol,
                signal_timestamp=datetime.utcnow(),
                signal_action=SignalAction.HOLD,
                signal_confidence=0.0,
                validation_status=ValidationStatus.INVALID,
                validation_score=0.0,
                validation_details={"error": str(e)}
            )
            signal_validations.append(error_validation)
        
        return signal_validations
    
    async def _generate_signals_for_data(self, strategy, mock_data: pd.DataFrame, 
                                       symbol: str, config: Dict[str, Any]) -> List[Dict[str, Any]]:
        """Generate signals for given market data"""
        signals = []
        
        # Use a sliding window approach to generate signals
        lookback_periods = config.get('lookback_periods', 20)
        
        for i in range(lookback_periods, len(mock_data)):
            # Get data window
            data_window = mock_data.iloc[i-lookback_periods:i]
            current_timestamp = mock_data.iloc[i].name
            
            try:
                # Generate signal
                signal = await strategy.generate_signal(symbol, data_window, str(current_timestamp))
                
                if signal:
                    signal_data = {
                        'signal': signal,
                        'timestamp': current_timestamp,
                        'data_window': data_window,
                        'current_price': mock_data.iloc[i]['close']
                    }
                    signals.append(signal_data)
            
            except Exception as e:
                # Log error but continue
                print(f"Error generating signal at index {i}: {str(e)}")
                continue
        
        return signals
    
    async def _validate_single_signal(self, signal_data: Dict[str, Any], 
                                    mock_data: pd.DataFrame, symbol: str, 
                                    config: Dict[str, Any]) -> SignalValidation:
        """Validate a single signal"""
        signal = signal_data['signal']
        timestamp = signal_data['timestamp']
        data_window = signal_data['data_window']
        current_price = signal_data['current_price']
        
        # Extract signal information
        signal_action = signal.action if hasattr(signal, 'action') else SignalAction.HOLD
        signal_confidence = signal.confidence if hasattr(signal, 'confidence') else 0.5
        
        # Initialize validation
        validation_status = ValidationStatus.VALID
        validation_score = 0.0
        timing_accuracy = None
        consistency_score = None
        edge_case_handling = None
        validation_details = {}
        
        try:
            # Validate signal action
            if signal_action not in [SignalAction.BUY, SignalAction.SELL, SignalAction.HOLD]:
                validation_status = ValidationStatus.INVALID
                validation_details['action_error'] = f"Invalid action: {signal_action}"
            
            # Validate signal confidence
            if not (0.0 <= signal_confidence <= 1.0):
                validation_status = ValidationStatus.INVALID
                validation_details['confidence_error'] = f"Invalid confidence: {signal_confidence}"
            
            # Test timing accuracy
            timing_accuracy = await self._test_signal_timing(signal, data_window, timestamp)
            
            # Test consistency
            consistency_score = await self._test_signal_consistency(signal, data_window, config)
            
            # Test edge case handling
            edge_case_handling = await self._test_edge_case_handling(signal, data_window, config)
            
            # Calculate overall validation score
            validation_score = await self._calculate_validation_score(
                signal_action, signal_confidence, timing_accuracy, 
                consistency_score, edge_case_handling
            )
            
            # Determine final validation status
            if validation_score < 50.0:
                validation_status = ValidationStatus.INVALID
            elif validation_score < 75.0:
                validation_status = ValidationStatus.AMBIGUOUS
            
            # Add validation details
            validation_details.update({
                'timing_accuracy': timing_accuracy,
                'consistency_score': consistency_score,
                'edge_case_handling': edge_case_handling,
                'validation_score': validation_score
            })
            
        except Exception as e:
            validation_status = ValidationStatus.INVALID
            validation_details['validation_error'] = str(e)
        
        return SignalValidation(
            strategy_name=getattr(strategy, 'name', 'Unknown'),
            symbol=symbol,
            signal_timestamp=timestamp,
            signal_action=signal_action,
            signal_confidence=signal_confidence,
            validation_status=validation_status,
            validation_score=validation_score,
            timing_accuracy=timing_accuracy,
            consistency_score=consistency_score,
            edge_case_handling=edge_case_handling,
            validation_details=validation_details,
            market_conditions=self._analyze_market_conditions(data_window)
        )
    
    async def _test_signal_timing(self, signal, data_window: pd.DataFrame, 
                                timestamp) -> float:
        """Test signal timing accuracy"""
        try:
            # Simple timing test - check if signal aligns with price movement
            if len(data_window) < 2:
                return 0.0
            
            # Get recent price trend
            recent_prices = data_window['close'].tail(5)
            price_trend = (recent_prices.iloc[-1] - recent_prices.iloc[0]) / recent_prices.iloc[0]
            
            # Check if signal direction aligns with trend
            signal_direction = 0
            if hasattr(signal, 'action'):
                if signal.action == SignalAction.BUY:
                    signal_direction = 1
                elif signal.action == SignalAction.SELL:
                    signal_direction = -1
            
            # Calculate timing accuracy
            if abs(price_trend) > 0.01:  # Significant price movement
                if (signal_direction > 0 and price_trend > 0) or (signal_direction < 0 and price_trend < 0):
                    return 0.8  # Good timing
                else:
                    return 0.3  # Poor timing
            else:
                return 0.5  # Neutral timing for sideways movement
            
        except Exception:
            return 0.0
    
    async def _test_signal_consistency(self, signal, data_window: pd.DataFrame, 
                                     config: Dict[str, Any]) -> float:
        """Test signal consistency across similar conditions"""
        try:
            # Simple consistency test based on signal confidence
            confidence = getattr(signal, 'confidence', 0.5)
            
            # Check if confidence is reasonable for the market conditions
            volatility = data_window['close'].std() / data_window['close'].mean()
            
            if volatility > 0.05:  # High volatility
                if confidence > 0.8:
                    return 0.6  # Lower consistency score for high confidence in volatile conditions
                else:
                    return 0.8  # Higher consistency score for moderate confidence
            else:  # Low volatility
                if confidence > 0.7:
                    return 0.9  # High consistency score for confident signals in stable conditions
                else:
                    return 0.7  # Moderate consistency score
            
        except Exception:
            return 0.5
    
    async def _test_edge_case_handling(self, signal, data_window: pd.DataFrame, 
                                     config: Dict[str, Any]) -> float:
        """Test edge case handling"""
        try:
            edge_case_score = 1.0
            
            # Check for extreme price movements
            price_changes = data_window['close'].pct_change().abs()
            max_change = price_changes.max()
            
            if max_change > 0.1:  # 10% price change
                # Signal should be more conservative in extreme conditions
                confidence = getattr(signal, 'confidence', 0.5)
                if confidence > 0.9:
                    edge_case_score -= 0.3  # Too confident for extreme conditions
            
            # Check for low volume
            avg_volume = data_window['volume'].mean()
            recent_volume = data_window['volume'].tail(3).mean()
            
            if recent_volume < avg_volume * 0.5:  # Low volume
                # Signal should account for low liquidity
                action = getattr(signal, 'action', SignalAction.HOLD)
                if action != SignalAction.HOLD:
                    edge_case_score -= 0.2  # Should be more cautious with low volume
            
            # Check for gaps
            price_gaps = data_window['close'].shift(1) - data_window['open']
            significant_gaps = (price_gaps.abs() > data_window['close'].std()).sum()
            
            if significant_gaps > 0:
                # Should handle gaps appropriately
                edge_case_score -= 0.1 * significant_gaps
            
            return max(0.0, edge_case_score)
            
        except Exception:
            return 0.5
    
    async def _calculate_validation_score(self, signal_action: str, signal_confidence: float,
                                        timing_accuracy: float, consistency_score: float,
                                        edge_case_handling: float) -> float:
        """Calculate overall validation score"""
        try:
            # Weight different components
            weights = {
                'confidence': 0.3,
                'timing': 0.25,
                'consistency': 0.25,
                'edge_cases': 0.2
            }
            
            # Normalize confidence to 0-1 scale
            confidence_score = signal_confidence
            
            # Calculate weighted average
            score = (
                confidence_score * weights['confidence'] +
                (timing_accuracy or 0.5) * weights['timing'] +
                (consistency_score or 0.5) * weights['consistency'] +
                (edge_case_handling or 0.5) * weights['edge_cases']
            )
            
            return score * 100.0  # Convert to 0-100 scale
            
        except Exception:
            return 0.0
    
    def _analyze_market_conditions(self, data_window: pd.DataFrame) -> Dict[str, Any]:
        """Analyze market conditions from data window"""
        try:
            conditions = {}
            
            # Calculate volatility
            returns = data_window['close'].pct_change().dropna()
            volatility = returns.std() * (252 ** 0.5)  # Annualized
            conditions['volatility'] = 'high' if volatility > 0.3 else 'medium' if volatility > 0.15 else 'low'
            
            # Calculate trend
            price_change = (data_window['close'].iloc[-1] - data_window['close'].iloc[0]) / data_window['close'].iloc[0]
            conditions['trend'] = 'bullish' if price_change > 0.02 else 'bearish' if price_change < -0.02 else 'sideways'
            
            # Calculate volume pattern
            avg_volume = data_window['volume'].mean()
            recent_volume = data_window['volume'].tail(5).mean()
            conditions['volume'] = 'above_average' if recent_volume > avg_volume * 1.2 else 'below_average' if recent_volume < avg_volume * 0.8 else 'normal'
            
            return conditions
            
        except Exception:
            return {
                'volatility': 'unknown',
                'trend': 'unknown',
                'volume': 'unknown'
            }
    
    async def validate_signal_quality(self, signal_validations: List[SignalValidation]) -> Dict[str, Any]:
        """Validate overall signal quality from a batch of validations"""
        if not signal_validations:
            return {
                'quality_score': 0.0,
                'issues': ['No signals to validate'],
                'recommendations': []
            }
        
        # Calculate aggregate metrics
        total_signals = len(signal_validations)
        valid_signals = sum(1 for v in signal_validations if v.is_valid_signal())
        avg_confidence = sum(v.signal_confidence for v in signal_validations) / total_signals
        avg_validation_score = sum(v.validation_score for v in signal_validations) / total_signals
        
        # Identify issues
        issues = []
        if valid_signals / total_signals < 0.8:
            issues.append(f"Low validity rate: {valid_signals/total_signals:.1%}")
        
        if avg_confidence < 0.6:
            issues.append(f"Low average confidence: {avg_confidence:.2f}")
        
        if avg_validation_score < 70:
            issues.append(f"Low average validation score: {avg_validation_score:.1f}")
        
        # Generate recommendations
        recommendations = []
        if avg_confidence < 0.7:
            recommendations.append("Consider improving signal confidence calculation")
        
        if avg_validation_score < 80:
            recommendations.append("Review signal validation criteria and thresholds")
        
        # Calculate overall quality score
        quality_score = (valid_signals / total_signals * 0.4 + 
                        avg_confidence * 0.3 + 
                        avg_validation_score / 100.0 * 0.3) * 100
        
        return {
            'quality_score': quality_score,
            'total_signals': total_signals,
            'valid_signals': valid_signals,
            'validity_rate': valid_signals / total_signals,
            'average_confidence': avg_confidence,
            'average_validation_score': avg_validation_score,
            'issues': issues,
            'recommendations': recommendations
        }













