apiVersion: batch/v1
kind: Job
metadata:
  name: pg-backup-schema
  namespace: trading-system
spec:
  template:
    spec:
      containers:
      - name: pg-backup
        image: postgres:15
        command: ["/bin/sh", "-c"]
        args:
          - |
            export PGPASSWORD="$POSTGRES_PASSWORD"
            pg_dump -h $POSTGRES_HOST -U $POSTGRES_USER -d $POSTGRES_DB --schema-only -F c -f /backup/backup_schema.dump
            ls -lh /backup
            cat /backup/backup_schema.dump | base64
        env:
        - name: POSTGRES_HOST
          value: "timescaledb.trading-system.svc.cluster.local"
        - name: POSTGRES_DB
          value: "trading_bot"
        - name: POSTGRES_USER
          value: "trading_user"
        - name: POSTGRES_PASSWORD
          value: "trading_pass"
        volumeMounts:
        - name: backup
          mountPath: /backup
      restartPolicy: Never
      volumes:
      - name: backup
        emptyDir: {} 