apiVersion: v1
kind: Secret
metadata:
  name: vapid-keys
  namespace: trading-system
type: Opaque
stringData:
  vapid-public-key: BMj_GefoQ5atYrNzreOcNIiRnIYqlgVMIeWV6-j4ow_vkXDvuTGjPK3qNdsztIus5CrBym94v7Q3Vp6ZLLjBz9o
  vapid-private-key: MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQggFzWzNTO0dkNtFVfWyAMrnBq7Q7TKJtCzKhCzqFwQ_WhRANCAATI_xnn6EOWrWKzc63jnDSIkZyGKpYFTCHllevo-KMP75Fw77kxozyt6jXbM7SLrOQqwcpveL-0N1aemSy4wc_a 