"""add missing tables

Revision ID: 20250723_add_missing_tables
Revises: 65a77fa65587
Create Date: 2025-07-23 04:50:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20250723_add_missing_tables'
down_revision: Union[str, None] = '65a77fa65587'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create historical_news table
    op.create_table('historical_news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('impact_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('affected_symbols', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('news_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('provider_id', sa.String(length=100), nullable=True),
    sa.Column('ticker', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_news_published_at', 'historical_news', ['published_at'], unique=False)
    op.create_index('idx_news_event_type', 'historical_news', ['event_type'], unique=False)
    op.create_index('idx_news_source', 'historical_news', ['source'], unique=False)
    op.create_index('idx_news_ticker', 'historical_news', ['ticker'], unique=False)
    op.create_index('idx_news_sentiment', 'historical_news', ['sentiment_score'], unique=False)
    op.create_index('idx_news_impact', 'historical_news', ['impact_score'], unique=False)
    
    # Create news_cache table
    op.create_table('news_cache',
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('earliest_date', sa.DateTime(), nullable=True),
    sa.Column('latest_date', sa.DateTime(), nullable=True),
    sa.Column('total_articles', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'source')
    )
    op.create_index('idx_cache_symbol', 'news_cache', ['symbol'], unique=False)
    op.create_index('idx_cache_source', 'news_cache', ['source'], unique=False)
    
    # Create backtest_runs table (if not exists)
    op.create_table('backtest_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=50), nullable=False),
    sa.Column('strategy_name', sa.String(length=100), nullable=False),
    sa.Column('backtest_name', sa.String(length=200), nullable=True),
    sa.Column('symbols', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('initial_capital', sa.Float(), nullable=False),
    sa.Column('final_capital', sa.Float(), nullable=False),
    sa.Column('total_return', sa.Float(), nullable=False),
    sa.Column('total_return_pct', sa.Float(), nullable=False),
    sa.Column('max_drawdown_pct', sa.Float(), nullable=False),
    sa.Column('sharpe_ratio', sa.Float(), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('winning_trades', sa.Integer(), nullable=False),
    sa.Column('losing_trades', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('profit_factor', sa.Float(), nullable=False),
    sa.Column('avg_win', sa.Float(), nullable=False),
    sa.Column('avg_loss', sa.Float(), nullable=False),
    sa.Column('database_only', sa.String(length=5), nullable=False),
    sa.Column('data_provider', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_index('idx_created_at', 'backtest_runs', ['created_at'], unique=False)
    op.create_index('idx_date_range', 'backtest_runs', ['start_date', 'end_date'], unique=False)
    op.create_index('idx_run_id', 'backtest_runs', ['run_id'], unique=False)
    op.create_index('idx_strategy', 'backtest_runs', ['strategy_name'], unique=False)
    op.create_index('idx_backtest_name', 'backtest_runs', ['backtest_name'], unique=False)
    
    # Create backtest_trades table (if not exists)
    op.create_table('backtest_trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('portfolio_value', sa.Float(), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('position_value', sa.Float(), nullable=False),
    sa.Column('total_pnl', sa.Float(), nullable=False),
    sa.Column('trade_pnl', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_action', 'backtest_trades', ['action'], unique=False)
    op.create_index('idx_run_id', 'backtest_trades', ['run_id'], unique=False)
    op.create_index('idx_symbol', 'backtest_trades', ['symbol'], unique=False)
    op.create_index('idx_timestamp', 'backtest_trades', ['timestamp'], unique=False)
    
    # Create backtest_equity_curves table (if not exists)
    op.create_table('backtest_equity_curves',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('portfolio_value', sa.Float(), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('positions_value', sa.Float(), nullable=False),
    sa.Column('total_pnl', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_date', 'backtest_equity_curves', ['date'], unique=False)
    op.create_index('idx_run_id', 'backtest_equity_curves', ['run_id'], unique=False)
    
    # Create additional trading tables
    op.create_table('trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('strategy', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trades_timestamp', 'trades', ['timestamp'], unique=False)
    op.create_index('idx_trades_symbol', 'trades', ['symbol'], unique=False)
    op.create_index('idx_trades_action', 'trades', ['action'], unique=False)
    op.create_index('idx_trades_strategy', 'trades', ['strategy'], unique=False)
    
    # Create orders table
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=False, unique=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('strategy', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_orders_timestamp', 'orders', ['timestamp'], unique=False)
    op.create_index('idx_orders_symbol', 'orders', ['symbol'], unique=False)
    op.create_index('idx_orders_status', 'orders', ['status'], unique=False)
    op.create_index('idx_orders_strategy', 'orders', ['strategy'], unique=False)
    
    # Create signals table
    op.create_table('signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('signal_type', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('strength', sa.Float(), nullable=True),
    sa.Column('strategy', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_signals_timestamp', 'signals', ['timestamp'], unique=False)
    op.create_index('idx_signals_symbol', 'signals', ['symbol'], unique=False)
    op.create_index('idx_signals_type', 'signals', ['signal_type'], unique=False)
    op.create_index('idx_signals_strategy', 'signals', ['strategy'], unique=False)
    
    # Create risk_metrics table
    op.create_table('risk_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('portfolio_value', sa.Float(), nullable=False),
    sa.Column('total_pnl', sa.Float(), nullable=False),
    sa.Column('daily_pnl', sa.Float(), nullable=False),
    sa.Column('max_drawdown', sa.Float(), nullable=False),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('var_95', sa.Float(), nullable=True),
    sa.Column('volatility', sa.Float(), nullable=True),
    sa.Column('beta', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_risk_metrics_date', 'risk_metrics', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_risk_metrics_date', table_name='risk_metrics')
    op.drop_table('risk_metrics')
    op.drop_index('idx_signals_strategy', table_name='signals')
    op.drop_index('idx_signals_type', table_name='signals')
    op.drop_index('idx_signals_symbol', table_name='signals')
    op.drop_index('idx_signals_timestamp', table_name='signals')
    op.drop_table('signals')
    op.drop_index('idx_orders_strategy', table_name='orders')
    op.drop_index('idx_orders_status', table_name='orders')
    op.drop_index('idx_orders_symbol', table_name='orders')
    op.drop_index('idx_orders_timestamp', table_name='orders')
    op.drop_table('orders')
    op.drop_index('idx_trades_strategy', table_name='trades')
    op.drop_index('idx_trades_action', table_name='trades')
    op.drop_index('idx_trades_symbol', table_name='trades')
    op.drop_index('idx_trades_timestamp', table_name='trades')
    op.drop_table('trades')
    op.drop_index('idx_run_id', table_name='backtest_equity_curves')
    op.drop_index('idx_date', table_name='backtest_equity_curves')
    op.drop_table('backtest_equity_curves')
    op.drop_index('idx_timestamp', table_name='backtest_trades')
    op.drop_index('idx_symbol', table_name='backtest_trades')
    op.drop_index('idx_run_id', table_name='backtest_trades')
    op.drop_index('idx_action', table_name='backtest_trades')
    op.drop_table('backtest_trades')
    op.drop_index('idx_backtest_name', table_name='backtest_runs')
    op.drop_index('idx_strategy', table_name='backtest_runs')
    op.drop_index('idx_run_id', table_name='backtest_runs')
    op.drop_index('idx_date_range', table_name='backtest_runs')
    op.drop_index('idx_created_at', table_name='backtest_runs')
    op.drop_table('backtest_runs')
    op.drop_index('idx_cache_source', table_name='news_cache')
    op.drop_index('idx_cache_symbol', table_name='news_cache')
    op.drop_table('news_cache')
    op.drop_index('idx_news_impact', table_name='historical_news')
    op.drop_index('idx_news_sentiment', table_name='historical_news')
    op.drop_index('idx_news_ticker', table_name='historical_news')
    op.drop_index('idx_news_source', table_name='historical_news')
    op.drop_index('idx_news_event_type', table_name='historical_news')
    op.drop_index('idx_news_published_at', table_name='historical_news')
    op.drop_table('historical_news')
    # ### end Alembic commands ### 