"""add news tables

Revision ID: 20250706015740
Revises: 65a77fa65587
Create Date: 2025-07-06 01:57:40.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20250706015740'
down_revision: Union[str, None] = '65a77fa65587'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('impact_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('affected_symbols', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('news_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('provider_id', sa.String(length=100), nullable=True),
    sa.Column('ticker', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_news_event_type', 'historical_news', ['event_type'], unique=False)
    op.create_index('idx_news_impact', 'historical_news', ['impact_score'], unique=False)
    op.create_index('idx_news_published_at', 'historical_news', ['published_at'], unique=False)
    op.create_index('idx_news_sentiment', 'historical_news', ['sentiment_score'], unique=False)
    op.create_index('idx_news_source', 'historical_news', ['source'], unique=False)
    op.create_index('idx_news_ticker', 'historical_news', ['ticker'], unique=False)
    op.create_table('news_cache',
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('earliest_date', sa.DateTime(), nullable=True),
    sa.Column('latest_date', sa.DateTime(), nullable=True),
    sa.Column('total_articles', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'source')
    )
    # Create indexes with IF NOT EXISTS handling
    try:
        op.create_index('idx_cache_source', 'news_cache', ['source'], unique=False)
    except Exception:
        pass  # Index might already exist
    try:
        op.create_index('idx_cache_symbol', 'news_cache', ['symbol'], unique=False)
    except Exception:
        pass  # Index might already exist
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_cache_symbol', table_name='news_cache')
    op.drop_index('idx_cache_source', table_name='news_cache')
    op.drop_table('news_cache')
    op.drop_index('idx_news_ticker', table_name='historical_news')
    op.drop_index('idx_news_source', table_name='historical_news')
    op.drop_index('idx_news_sentiment', table_name='historical_news')
    op.drop_index('idx_news_published_at', table_name='historical_news')
    op.drop_index('idx_news_impact', table_name='historical_news')
    op.drop_index('idx_news_event_type', table_name='historical_news')
    op.drop_table('historical_news')
    # ### end Alembic commands ### 