"""initial schema

Revision ID: 65a77fa65587
Revises: 
Create Date: 2025-07-05 14:08:48.532857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65a77fa65587'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_equity_curves',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('portfolio_value', sa.Float(), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('positions_value', sa.Float(), nullable=False),
    sa.Column('total_pnl', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_date', 'backtest_equity_curves', ['date'], unique=False)
    op.create_index('idx_run_id', 'backtest_equity_curves', ['run_id'], unique=False)
    op.create_table('backtest_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=50), nullable=False),
    sa.Column('strategy_name', sa.String(length=100), nullable=False),
    sa.Column('symbols', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('initial_capital', sa.Float(), nullable=False),
    sa.Column('final_capital', sa.Float(), nullable=False),
    sa.Column('total_return', sa.Float(), nullable=False),
    sa.Column('total_return_pct', sa.Float(), nullable=False),
    sa.Column('max_drawdown_pct', sa.Float(), nullable=False),
    sa.Column('sharpe_ratio', sa.Float(), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('winning_trades', sa.Integer(), nullable=False),
    sa.Column('losing_trades', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('profit_factor', sa.Float(), nullable=False),
    sa.Column('avg_win', sa.Float(), nullable=False),
    sa.Column('avg_loss', sa.Float(), nullable=False),
    sa.Column('database_only', sa.String(length=5), nullable=False),
    sa.Column('data_provider', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_index('idx_created_at', 'backtest_runs', ['created_at'], unique=False)
    op.create_index('idx_date_range', 'backtest_runs', ['start_date', 'end_date'], unique=False)
    op.create_index('idx_run_id', 'backtest_runs', ['run_id'], unique=False)
    op.create_index('idx_strategy', 'backtest_runs', ['strategy_name'], unique=False)
    op.create_table('backtest_trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('portfolio_value', sa.Float(), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('position_value', sa.Float(), nullable=False),
    sa.Column('total_pnl', sa.Float(), nullable=False),
    sa.Column('trade_pnl', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_action', 'backtest_trades', ['action'], unique=False)
    op.create_index('idx_run_id', 'backtest_trades', ['run_id'], unique=False)
    op.create_index('idx_symbol', 'backtest_trades', ['symbol'], unique=False)
    op.create_index('idx_timestamp', 'backtest_trades', ['timestamp'], unique=False)
    op.drop_index('idx_date_range', table_name='historical_prices')
    op.drop_index('idx_provider_symbol', table_name='historical_prices')
    op.drop_index('idx_symbol_date', table_name='historical_prices')
    op.drop_table('historical_prices')
    op.drop_index('idx_cache_provider', table_name='market_data_cache')
    op.drop_index('idx_cache_symbol', table_name='market_data_cache')
    op.drop_table('market_data_cache')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_data_cache',
    sa.Column('symbol', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('interval', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('earliest_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('latest_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('total_records', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'provider', 'interval', name='market_data_cache_pkey')
    )
    op.create_index('idx_cache_symbol', 'market_data_cache', ['symbol'], unique=False)
    op.create_index('idx_cache_provider', 'market_data_cache', ['provider'], unique=False)
    op.create_table('historical_prices',
    sa.Column('symbol', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('open_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('high_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('low_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('close_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('volume', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('interval', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'date', name='historical_prices_pkey')
    )
    op.create_index('idx_symbol_date', 'historical_prices', ['symbol', 'date'], unique=False)
    op.create_index('idx_provider_symbol', 'historical_prices', ['provider', 'symbol'], unique=False)
    op.create_index('idx_date_range', 'historical_prices', ['date'], unique=False)
    op.drop_index('idx_timestamp', table_name='backtest_trades')
    op.drop_index('idx_symbol', table_name='backtest_trades')
    op.drop_index('idx_run_id', table_name='backtest_trades')
    op.drop_index('idx_action', table_name='backtest_trades')
    op.drop_table('backtest_trades')
    op.drop_index('idx_strategy', table_name='backtest_runs')
    op.drop_index('idx_run_id', table_name='backtest_runs')
    op.drop_index('idx_date_range', table_name='backtest_runs')
    op.drop_index('idx_created_at', table_name='backtest_runs')
    op.drop_table('backtest_runs')
    op.drop_index('idx_run_id', table_name='backtest_equity_curves')
    op.drop_index('idx_date', table_name='backtest_equity_curves')
    op.drop_table('backtest_equity_curves')
    # ### end Alembic commands ###
