"""
Compliance Report Data Model

Represents regulatory compliance status and audit trail for the comprehensive
risk management framework.
"""

from dataclasses import dataclass, field
from datetime import datetime, date
from typing import Dict, Any, List, Optional
from uuid import uuid4, UUID
from enum import Enum


class ReportType(Enum):
    """Types of compliance reports."""
    DAILY = "daily"
    WEEKLY = "weekly"
    MONTHLY = "monthly"
    AD_HOC = "ad_hoc"


class ComplianceStatus(Enum):
    """Overall compliance status."""
    COMPLIANT = "compliant"
    WARNING = "warning"
    VIOLATION = "violation"


class ReportFormat(Enum):
    """Supported report formats."""
    PDF = "PDF"
    CSV = "CSV"
    JSON = "JSON"


@dataclass
class ComplianceReport:
    """
    Regulatory compliance status and audit trail.
    
    This model represents comprehensive compliance reports including
    trade documentation, audit trails, and regulatory status.
    """
    
    # Primary key
    compliance_report_id: UUID = field(default_factory=uuid4)
    
    # Portfolio reference
    portfolio_id: UUID = field()
    
    # Report metadata
    report_timestamp: datetime = field(default_factory=datetime.utcnow)
    report_type: ReportType = field()
    report_period_start: date = field()
    report_period_end: date = field()
    
    # Compliance status
    compliance_status: ComplianceStatus = field(default=ComplianceStatus.COMPLIANT)
    
    # Report content
    audit_trail: Dict[str, Any] = field(default_factory=dict)
    trade_documentation: Dict[str, Any] = field(default_factory=dict)
    position_reporting: Dict[str, Any] = field(default_factory=dict)
    risk_metrics_summary: Dict[str, Any] = field(default_factory=dict)
    regulatory_checks: Dict[str, Any] = field(default_factory=dict)
    violations_detected: List[Dict[str, Any]] = field(default_factory=list)
    recommendations: List[str] = field(default_factory=list)
    
    # Report generation
    report_format: ReportFormat = field(default=ReportFormat.JSON)
    report_file_path: Optional[str] = field(default=None)
    generated_by: str = field(default="system")
    reviewed_by: Optional[str] = field(default=None)
    review_timestamp: Optional[datetime] = field(default=None)
    
    # Timestamps
    created_at: datetime = field(default_factory=datetime.utcnow)
    
    def __post_init__(self) -> None:
        """Validate data after initialization."""
        self.validate()
    
    def validate(self) -> None:
        """Validate compliance report data."""
        if not isinstance(self.portfolio_id, UUID):
            raise ValueError("Portfolio ID must be a valid UUID")
        
        if not isinstance(self.report_type, ReportType):
            raise ValueError("Report type must be a valid ReportType")
        
        if not isinstance(self.compliance_status, ComplianceStatus):
            raise ValueError("Compliance status must be a valid ComplianceStatus")
        
        if not isinstance(self.report_format, ReportFormat):
            raise ValueError("Report format must be a valid ReportFormat")
        
        if self.report_period_end <= self.report_period_start:
            raise ValueError("Report period end must be after report period start")
        
        if not self.generated_by:
            raise ValueError("Generated by field is required")
        
        if self.reviewed_by and not self.review_timestamp:
            raise ValueError("Review timestamp is required when reviewed_by is set")
        
        if self.review_timestamp and not self.reviewed_by:
            raise ValueError("Reviewed by is required when review_timestamp is set")
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert ComplianceReport to dictionary."""
        return {
            "compliance_report_id": str(self.compliance_report_id),
            "portfolio_id": str(self.portfolio_id),
            "report_timestamp": self.report_timestamp.isoformat(),
            "report_type": self.report_type.value,
            "report_period_start": self.report_period_start.isoformat(),
            "report_period_end": self.report_period_end.isoformat(),
            "compliance_status": self.compliance_status.value,
            "audit_trail": self.audit_trail,
            "trade_documentation": self.trade_documentation,
            "position_reporting": self.position_reporting,
            "risk_metrics_summary": self.risk_metrics_summary,
            "regulatory_checks": self.regulatory_checks,
            "violations_detected": self.violations_detected,
            "recommendations": self.recommendations,
            "report_format": self.report_format.value,
            "report_file_path": self.report_file_path,
            "generated_by": self.generated_by,
            "reviewed_by": self.reviewed_by,
            "review_timestamp": self.review_timestamp.isoformat() if self.review_timestamp else None,
            "created_at": self.created_at.isoformat()
        }
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "ComplianceReport":
        """Create ComplianceReport from dictionary."""
        # Convert UUID strings back to UUID objects
        if isinstance(data.get("compliance_report_id"), str):
            data["compliance_report_id"] = UUID(data["compliance_report_id"])
        if isinstance(data.get("portfolio_id"), str):
            data["portfolio_id"] = UUID(data["portfolio_id"])
        
        # Convert enum strings back to enum objects
        if isinstance(data.get("report_type"), str):
            data["report_type"] = ReportType(data["report_type"])
        if isinstance(data.get("compliance_status"), str):
            data["compliance_status"] = ComplianceStatus(data["compliance_status"])
        if isinstance(data.get("report_format"), str):
            data["report_format"] = ReportFormat(data["report_format"])
        
        # Convert date strings back to date objects
        for field in ["report_period_start", "report_period_end"]:
            if isinstance(data.get(field), str):
                data[field] = date.fromisoformat(data[field])
        
        # Convert datetime strings back to datetime objects
        for field in ["report_timestamp", "review_timestamp", "created_at"]:
            if data.get(field) and isinstance(data[field], str):
                data[field] = datetime.fromisoformat(data[field].replace("Z", "+00:00"))
        
        return cls(**data)
    
    def get_compliance_summary(self) -> Dict[str, Any]:
        """Get a summary of compliance status."""
        return {
            "compliance_status": self.compliance_status.value,
            "report_type": self.report_type.value,
            "report_period_start": self.report_period_start.isoformat(),
            "report_period_end": self.report_period_end.isoformat(),
            "violations_count": len(self.violations_detected),
            "recommendations_count": len(self.recommendations),
            "generated_by": self.generated_by,
            "reviewed_by": self.reviewed_by,
            "is_reviewed": self.reviewed_by is not None
        }
    
    def add_violation(self, violation_type: str, description: str, severity: str = "medium") -> None:
        """Add a compliance violation to the report."""
        violation = {
            "violation_type": violation_type,
            "description": description,
            "severity": severity,
            "timestamp": datetime.utcnow().isoformat()
        }
        self.violations_detected.append(violation)
        
        # Update compliance status if needed
        if self.compliance_status == ComplianceStatus.COMPLIANT:
            if severity in ["high", "critical"]:
                self.compliance_status = ComplianceStatus.VIOLATION
            else:
                self.compliance_status = ComplianceStatus.WARNING
    
    def add_recommendation(self, recommendation: str) -> None:
        """Add a compliance recommendation to the report."""
        if recommendation not in self.recommendations:
            self.recommendations.append(recommendation)
    
    def mark_reviewed(self, reviewed_by: str) -> None:
        """Mark the report as reviewed."""
        self.reviewed_by = reviewed_by
        self.review_timestamp = datetime.utcnow()
    
    def is_reviewed(self) -> bool:
        """Check if the report has been reviewed."""
        return self.reviewed_by is not None
    
    def get_violations_by_severity(self) -> Dict[str, List[Dict[str, Any]]]:
        """Get violations grouped by severity."""
        violations_by_severity = {
            "low": [],
            "medium": [],
            "high": [],
            "critical": []
        }
        
        for violation in self.violations_detected:
            severity = violation.get("severity", "medium")
            if severity in violations_by_severity:
                violations_by_severity[severity].append(violation)
        
        return violations_by_severity
    
    def has_critical_violations(self) -> bool:
        """Check if the report has any critical violations."""
        return any(
            violation.get("severity") == "critical"
            for violation in self.violations_detected
        )
    
    def get_report_filename(self) -> str:
        """Generate a filename for the report."""
        period_str = f"{self.report_period_start.isoformat()}_to_{self.report_period_end.isoformat()}"
        return f"compliance_report_{self.report_type.value}_{period_str}.{self.report_format.value.lower()}"
    
    def __str__(self) -> str:
        """String representation of ComplianceReport."""
        return (f"ComplianceReport(portfolio_id={self.portfolio_id}, "
                f"type={self.report_type.value}, "
                f"status={self.compliance_status.value}, "
                f"violations={len(self.violations_detected)})")
    
    def __repr__(self) -> str:
        """Detailed string representation of ComplianceReport."""
        return (f"ComplianceReport("
                f"compliance_report_id={self.compliance_report_id}, "
                f"portfolio_id={self.portfolio_id}, "
                f"report_type={self.report_type.value}, "
                f"compliance_status={self.compliance_status.value}, "
                f"report_period_start={self.report_period_start}, "
                f"report_period_end={self.report_period_end})")
























